name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Npm Install
        run: |
          npm install

      - name: Test
        run: |
          npm run test
